name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
        working-directory: todo-firebase
      - name: Lint
        run: npm run lint
        working-directory: todo-firebase
      - name: Build
        run: npm run build -- --prod
        working-directory: todo-firebase
      - name: Test
        run: npm test -- --configuration=ci
        working-directory: todo-firebase
